---
frameworkVersion: ">=1.28.0 <2.0.0"

service: lambda-sqs-example

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'staging'}
  region: ${env:AWS_REGION}

package:
  exclude:
    - ./**
  include:
    - ./worker.py

functions:
  worker:
    handler: worker.handler
    timeout: 25
    reservedConcurrency: 10
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn
          batchSize: 1

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}
        VisibilityTimeout: 30
