---
# Requires https://serverless.com/blog/serverless-updates-framework-v128/ or later

service: lambda-sqs-example

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'staging'}
  region: ${env:AWS_REGION}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  worker:
    handler: bin/worker
    reservedConcurrency: 10
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn
          batchSize: 1

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}
